In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

x = [0, 3, 4, 2]
y = [0.2, 0.9, 0.8, 0.9]

fig.add_trace(
    go.Scatter(
        x=x,
        y=y,
        #mode="lines",
        name="Temperature"
    )
)

fig.update_layout(
    title="Simulation Result",
    xaxis_title="Time [s]",
    yaxis_title="Temperature [°C]"
)


In [ ]:
import numpy as np
from qewton.visualization.plot import *
# batch x height x width
images = 255 * np.random.rand(20, 64, 64, 3)

batch = SliderAxis(0, "batch")

config = PlotConfiguration([
    batch,
    XAxis('x'),
    YAxis('y'),
    ColorAxis("gray")
])

plot = ImagePlot(
    images,
    plot_config=config,
    title="Batch images"
)

fig = Figure([plot])

fig.show()

print(len(fig.backend_figure.data))

# ----------------------------
# later
# ----------------------------

# batch.state = 5

# batch.state = 12

# batch.state = 19

[[[ 50.82733406  17.63395965 147.22558197]
  [ 70.56246461 174.22322869  65.65671468]
  [ 11.72809713   8.97555999  69.01713281]
  ...
  [147.38921222  64.46215329 103.16535968]
  [202.32755452  83.76470434 252.23582872]
  [128.28613306 155.72983195 205.9265246 ]]

 [[ 65.80062237 218.89213314 171.22773871]
  [  9.72413287 139.10201849  50.20944392]
  [  2.47110996  46.47871144 248.07388556]
  ...
  [222.68212438 246.81421753 101.47778805]
  [226.88714042 138.37618328  45.14690172]
  [ 40.57267292 149.84940181  75.85716482]]

 [[223.31045568   2.76652172  23.69169541]
  [140.20510339  38.67201803 247.93824259]
  [162.95046231  14.24916147 119.27471469]
  ...
  [224.32261336 212.39975466 223.38901213]
  [ 37.48964553  65.98734435 168.31281512]
  [223.00977241 131.82618607 131.87434135]]

 ...

 [[112.95013166 142.48678553 245.99529318]
  [231.75055066 164.30161799  58.89270729]
  [ 53.46092846 116.66247745 165.08711779]
  ...
  [149.1651259  196.73598446 100.55704518]
  [204.2903168   3

1


In [ ]:
import ipywidgets as widgets
from IPython.display import display

slider = widgets.IntSlider(
    min=0,
    max=images.shape[0]-1,
    value=batch.state,
    description="Batch"
)

def on_change(change):
    if change["name"] == "value":
        batch.state = change["new"]

fig.show()

slider.observe(on_change)

display(slider)


IntSlider(value=5, description='Batch', max=19)

In [ ]:
from dash import Dash, dcc, html, Input, Output, callback

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    dcc.Slider(0, 20, 1,
               value=10,
               id='my-slider'
    ),
    html.Div(id='slider-output-container')
])

@callback(
    Output('slider-output-container', 'children'),
    Input('my-slider', 'value'))
def update_output(value):
    return 'You have selected "{}"'.format(value)

app.run(debug=True, jupyter_mode="external")

Dash app running on http://127.0.0.1:8050/


NameError: name 'PlotlyRenderer' is not defined

In [ ]:
import numpy as np

from dash import Dash, html, dcc
from dash.dependencies import Input, Output

from qewton.visualization import *
images = 255 * np.random.rand(20, 128, 128, 1)


from qewton.config import Variable


batch = SliderAxis(
    Variable("batch", 1),    
    init_state=0,
    minimum=0,
    maximum=19,
    step=1,
)


X = Variable("x", dim=1)
Y = Variable("y", dim=1)
Z = Variable("z", dim=1)

config = PlotConfiguration(
    axes=[
        batch,
        XAxis(X),
        YAxis(Y),
        ZAxis(Z),
    ]
)

plot = SurfacePlot(
    images,
    config,
    title="Images",
)

figure = Figure(plot, title="Image Plot")

app = DashApplication.create(figure)

app.run(debug=True, jupyter_mode="external")

(128, 128, 3)
[0, 1]


ValueError: axes don't match array