In [3]:
import numpy as np
from qewton.config.axes import BatchAxes, FeatureAxes, GeometryAxes
from qewton.visualization import *
from qewton import DataConfiguration
images = 255 * np.random.rand(20, 128, 128, 2)


from qewton.config import Variable
import qewton

batch_axes = BatchAxes(20)

batch = SliderSpec(
    batch_axes,  
    init_state=0,
    minimum=0,
    maximum=19,
    step=1,
)


X = Variable("x", dim=1)
Y = Variable("y", dim=1)
Z = Variable("z", dim=1)
C = Variable("c", dim=1)

data_config = DataConfiguration(
    batch_axes,
    GeometryAxes(qewton.geometries.Geometry(X*Y, shape=(128, 128))),
    FeatureAxes(Z * C))

plot = SurfacePlot(
    images,
    data_config,
    x = X,
    y = Y,
    color = C,
    controls = [batch]
)

figure = Figure(plot, title="Image Plot")

app = DashApplication.create(figure)

app.run(debug=True, jupyter_mode="external")

(128, 128, 2)
x1 x1
x1 y1
y1 y1
z1 c1
c1 c1
(128, 128, 2)
[[[ 16.75055962]
  [106.72944237]
  [ 87.47022947]
  ...
  [ 52.81810037]
  [109.19069978]
  [198.04135292]]

 [[175.38028716]
  [120.90295344]
  [244.2337792 ]
  ...
  [  5.31809613]
  [ 90.05406809]
  [ 61.72135051]]

 [[181.72810811]
  [ 43.73625259]
  [106.88521617]
  ...
  [117.75934978]
  [204.85512173]
  [145.56257508]]

 ...

 [[213.96505777]
  [113.48612021]
  [ 62.21446701]
  ...
  [234.90001167]
  [159.45118297]
  [237.8468802 ]]

 [[ 78.64931522]
  [121.00993106]
  [253.10152401]
  ...
  [  8.58785425]
  [ 27.32128442]
  [148.3758433 ]]

 [[101.25360181]
  [249.07703646]
  [ 98.28524024]
  ...
  [171.44598166]
  [ 57.64168492]
  [ 45.23762448]]]
Dash app running on http://127.0.0.1:8050/
