In [ ]:
import numpy as np
from qewton.config.axes import BatchAxes, FeatureAxes, GeometryAxes
from qewton.visualization import *
from qewton import DataConfiguration
images = 255 * np.random.rand(20, 128, 128, 2)


from qewton.config import Variable
import qewton

batch_axes = BatchAxes(20)

batch = SliderSpec(
    batch_axes,  
    init_state=0,
    minimum=0,
    maximum=19,
    step=1,
)


X = Variable("x", dim=1)
Y = Variable("y", dim=1)
Z = Variable("z", dim=1)
C = Variable("c", dim=1)

data_config = DataConfiguration(
    batch_axes,
    GeometryAxes(qewton.geometries.Geometry(X*Y, shape=(128, 128))),
    FeatureAxes(Z * C))

plot = SurfacePlot(
    images,
    data_config,
    x = X,
    y = Y,
    z = AxisSpec(Z, log_scale=True),
    color = C,
    controls = [batch]
)

figure = Figure(plot, title="Image Plot")

app = DashApplication.create(figure)

app.run(debug=True, jupyter_mode="external")

(128, 128, 2)
x1 x1
x1 y1
y1 y1
z1 c1
c1 c1
z1 z1
(128, 128, 1)
[[[ 82.09185345]
  [ 40.47324121]
  [ 30.02743197]
  ...
  [ 93.72072303]
  [  3.26519856]
  [138.10036524]]

 [[ 66.67554871]
  [ 92.80229991]
  [191.0911886 ]
  ...
  [ 89.06106891]
  [ 71.89083655]
  [189.41687136]]

 [[204.33738704]
  [ 49.13848339]
  [ 87.57230219]
  ...
  [ 13.367947  ]
  [ 54.96343588]
  [117.55940419]]

 ...

 [[ 44.79900466]
  [ 43.04835446]
  [ 87.22987857]
  ...
  [239.84145131]
  [125.17027792]
  [107.93608107]]

 [[138.66256232]
  [ 78.68688502]
  [148.78878447]
  ...
  [199.57471508]
  [ 66.23464468]
  [ 65.00696445]]

 [[109.33263616]
  [240.92619337]
  [164.90386269]
  ...
  [ 59.61331021]
  [177.32665894]
  [ 77.29186566]]]
Dash app running on http://127.0.0.1:8050/


(128, 128, 2)
x1 x1
x1 y1
y1 y1
z1 c1
c1 c1
z1 z1
(128, 128, 1)
[[[ 82.09185345]
  [ 40.47324121]
  [ 30.02743197]
  ...
  [ 93.72072303]
  [  3.26519856]
  [138.10036524]]

 [[ 66.67554871]
  [ 92.80229991]
  [191.0911886 ]
  ...
  [ 89.06106891]
  [ 71.89083655]
  [189.41687136]]

 [[204.33738704]
  [ 49.13848339]
  [ 87.57230219]
  ...
  [ 13.367947  ]
  [ 54.96343588]
  [117.55940419]]

 ...

 [[ 44.79900466]
  [ 43.04835446]
  [ 87.22987857]
  ...
  [239.84145131]
  [125.17027792]
  [107.93608107]]

 [[138.66256232]
  [ 78.68688502]
  [148.78878447]
  ...
  [199.57471508]
  [ 66.23464468]
  [ 65.00696445]]

 [[109.33263616]
  [240.92619337]
  [164.90386269]
  ...
  [ 59.61331021]
  [177.32665894]
  [ 77.29186566]]]
(128, 128, 2)
x1 x1
x1 y1
y1 y1
z1 c1
c1 c1
z1 z1
(128, 128, 1)
[[[151.94281669]
  [248.73720664]
  [ 68.25060631]
  ...
  [ 94.22894436]
  [142.34791853]
  [246.83921557]]

 [[170.7499153 ]
  [130.68938691]
  [  1.73151196]
  ...
  [253.15361784]
  [144.8321061 ]
  [12